USE retailer_analysis;
select * from retailer_analysis;

# How many transactions were recorded?
select count(Distinct Transaction_ID) from retailer_analysis;

# total number of unique customers.
select count(Distinct Customer_ID) from retailer_analysis;

# the total revenue generated.
select round(sum(Total_amount),2) as 'total_revenue' from retailer_analysis;

# the average order value
select avg(Total_purchases) from retailer_analysis;

# month generated the highest revenue
select year,month,round(sum(Total_amount),2) as revenue from retailer_analysis
group by month,year
order by revenue desc
limit 1;

# the top 10 highest revenue dates.
select date ,round(sum(Total_amount),2) as revenue from retailer_analysis
group by date
order by revenue desc
limit 10;

# the top 10 highest-value transactions.
select Transaction_ID, round(sum(Total_amount),2) as total_revenue from retailer_analysis
group by Transaction_ID
order by total_revenue desc
limit 10;

#top 10 customers by total spending
select customer_id, round(sum(total_amount),2) as revenue from retailer_analysis
group by customer_id
order by revenue desc
limit 10;

# customers with more than five purchases
select customer_id, count(customer_id) as counts from retailer_analysis
group by customer_id
having counts>5;

# revenue generated by each customer segment
select customer_segment, round(sum(Total_Amount),2) as revenue
from retailer_analysis
group by customer_segment
order by revenue desc;

# customer distribution by gender.
select gender, count(distinct customer_id) customer_count
from retailer_analysis
group by gender;

# the average revenue generated by each age group
select age_group, round(avg(total_amount),2) as avg_revenue
from retailer_analysis
group by age_group
order by avg_revenue desc;

# Which product categories generate the highest revenue
select product_category, round(sum(Total_amount),2) as revenue
from retailer_analysis
group by product_category
order by revenue desc;

# average rating of each product category.
select product_category, round(avg(ratings),2) as rating
from retailer_analysis
group by product_category
order by rating desc;

# the top-selling product brands.
select product_brand, sum(total_purchases) as 'no_of_item_sale'
from retailer_analysis
group by product_brand
order by no_of_item_sale desc
limit 10;

# Which product types are most popular
select product_type, sum(total_purchases) as 'no of item_sale'
from retailer_analysis
group by product_type
order by sum(total_purchases) desc
limit 10;

# the top 10 products by revenue
select product_type, round(sum(total_amount),2) as 'revenue'
from retailer_analysis
group by product_type
order by sum(total_amount) desc
limit 10;

# payment method contributes the highest revenue
select payment_method, round(sum(total_amount),2) as revenue
from retailer_analysis
group by payment_method
order by revenue desc;

# revenue generated by each shipping method
select shipping_method, round(sum(total_amount),2) as revenue
from retailer_analysis
group by shipping_method
order by revenue desc;

#top 10 cities by revenue.
select city, round(sum(total_amount),2) as revenue
from retailer_analysis
group by city
order by sum(total_amount) desc
limit 10;

select customer_id, round(sum(total_amount),2) as total_spending
from retailer_analysis
group by customer_id
having sum(total_amount)>(
select avg(total_spending) from (
select sum(total_amount) as total_spending from retailer_analysis
group by customer_id) as avg_customer);

